author: "Robbert Brandsma & Joannis Orlandos"
module: BSON
readme: README.md
github_url: https://github.com/PlanTeam/BSON
swift_version: 2.2
xcodebuild_arguments:
  - "-scheme"
  - "BSON"
custom_categories:
  - name: BSON Types
    children:
    - Document
    - ObjectId
    - Binary
    - "Null"
    - Bool
    - Double
    - Int
    - Int32
    - Int64
    - NSData
    - NSDate
    - String
    - JavaScriptCode
    - MinKey
    - MaxKey
    - RegularExpression
    - Timestamp

  - name: Errors
    children:
    - DeserializationError

  - name: Used internally
    children:
    - BSONLength
    - ElementType
    - BSONElement
