# Borrowed from Vapor (https://github.com/qutheory/vapor)
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL swift.qutheory.io/travis)"
script:
  - swift build
  - swift build --configuration release
  - swift test
  